# Generated by Django 5.1.6 on 2025-02-08 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_article_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='img_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
