# Generated by Django 5.1.6 on 2025-02-10 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_article_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img_url',
            field=models.URLField(default=None),
        ),
    ]
