# Generated by Django 5.1.6 on 2025-03-19 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_article_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
